/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedCoverageRouteImport } from './routes/_authenticated/coverage'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSyncsRouteImport } from './routes/_authenticated/syncs'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedWebhooksRouteImport } from './routes/_authenticated/webhooks'
import { Route as WidgetConnectRouteImport } from './routes/widget.connect'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedSettingsTabRouteImport } from './routes/_authenticated/settings/$tab'
import { Route as AuthenticatedSyncsIndexRouteImport } from './routes/_authenticated/syncs/index'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedUsersUserIdRouteImport } from './routes/_authenticated/users/$userId'
import { Route as AuthenticatedWebhooksIndexRouteImport } from './routes/_authenticated/webhooks/index'
import { Route as AuthenticatedWebhooksEndpointIdRouteImport } from './routes/_authenticated/webhooks/$endpointId'
import { Route as UsersUserIdPairRouteImport } from './routes/users/$userId/pair'
import { Route as AuthenticatedUsersUserIdIndexRouteImport } from './routes/_authenticated/users/$userId/index'
import { Route as AuthenticatedUsersUserIdTabRouteImport } from './routes/_authenticated/users/$userId/$tab'
import { Route as AuthenticatedWebhooksEndpointIdIndexRouteImport } from './routes/_authenticated/webhooks/$endpointId/index'
import { Route as AuthenticatedWebhooksEndpointIdTabRouteImport } from './routes/_authenticated/webhooks/$endpointId/$tab'
import { Route as UsersUserIdPairIndexRouteImport } from './routes/users/$userId/pair.index'
import { Route as UsersUserIdPairErrorRouteImport } from './routes/users/$userId/pair.error'
import { Route as UsersUserIdPairSuccessRouteImport } from './routes/users/$userId/pair.success'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCoverageRoute = AuthenticatedCoverageRouteImport.update({
  id: '/coverage',
  path: '/coverage',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSyncsRoute = AuthenticatedSyncsRouteImport.update({
  id: '/syncs',
  path: '/syncs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWebhooksRoute = AuthenticatedWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const WidgetConnectRoute = WidgetConnectRouteImport.update({
  id: '/widget/connect',
  path: '/widget/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsTabRoute =
  AuthenticatedSettingsTabRouteImport.update({
    id: '/$tab',
    path: '/$tab',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSyncsIndexRoute = AuthenticatedSyncsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedSyncsRoute,
} as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedUsersRoute,
} as any)
const AuthenticatedUsersUserIdRoute =
  AuthenticatedUsersUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => AuthenticatedUsersRoute,
  } as any)
const AuthenticatedWebhooksIndexRoute =
  AuthenticatedWebhooksIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWebhooksRoute,
  } as any)
const AuthenticatedWebhooksEndpointIdRoute =
  AuthenticatedWebhooksEndpointIdRouteImport.update({
    id: '/$endpointId',
    path: '/$endpointId',
    getParentRoute: () => AuthenticatedWebhooksRoute,
  } as any)
const UsersUserIdPairRoute = UsersUserIdPairRouteImport.update({
  id: '/users/$userId/pair',
  path: '/users/$userId/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersUserIdIndexRoute =
  AuthenticatedUsersUserIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedUsersUserIdRoute,
  } as any)
const AuthenticatedUsersUserIdTabRoute =
  AuthenticatedUsersUserIdTabRouteImport.update({
    id: '/$tab',
    path: '/$tab',
    getParentRoute: () => AuthenticatedUsersUserIdRoute,
  } as any)
const AuthenticatedWebhooksEndpointIdIndexRoute =
  AuthenticatedWebhooksEndpointIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWebhooksEndpointIdRoute,
  } as any)
const AuthenticatedWebhooksEndpointIdTabRoute =
  AuthenticatedWebhooksEndpointIdTabRouteImport.update({
    id: '/$tab',
    path: '/$tab',
    getParentRoute: () => AuthenticatedWebhooksEndpointIdRoute,
  } as any)
const UsersUserIdPairIndexRoute = UsersUserIdPairIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsersUserIdPairRoute,
} as any)
const UsersUserIdPairErrorRoute = UsersUserIdPairErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => UsersUserIdPairRoute,
} as any)
const UsersUserIdPairSuccessRoute = UsersUserIdPairSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => UsersUserIdPairRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/coverage': typeof AuthenticatedCoverageRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/syncs': typeof AuthenticatedSyncsRouteWithChildren
  '/users': typeof AuthenticatedUsersRouteWithChildren
  '/webhooks': typeof AuthenticatedWebhooksRouteWithChildren
  '/widget/connect': typeof WidgetConnectRoute
  '/settings/$tab': typeof AuthenticatedSettingsTabRoute
  '/users/$userId': typeof AuthenticatedUsersUserIdRouteWithChildren
  '/webhooks/$endpointId': typeof AuthenticatedWebhooksEndpointIdRouteWithChildren
  '/users/$userId/pair': typeof UsersUserIdPairRouteWithChildren
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/syncs/': typeof AuthenticatedSyncsIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/webhooks/': typeof AuthenticatedWebhooksIndexRoute
  '/users/$userId/$tab': typeof AuthenticatedUsersUserIdTabRoute
  '/webhooks/$endpointId/$tab': typeof AuthenticatedWebhooksEndpointIdTabRoute
  '/users/$userId/pair/error': typeof UsersUserIdPairErrorRoute
  '/users/$userId/pair/success': typeof UsersUserIdPairSuccessRoute
  '/users/$userId/': typeof AuthenticatedUsersUserIdIndexRoute
  '/webhooks/$endpointId/': typeof AuthenticatedWebhooksEndpointIdIndexRoute
  '/users/$userId/pair/': typeof UsersUserIdPairIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/coverage': typeof AuthenticatedCoverageRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/widget/connect': typeof WidgetConnectRoute
  '/settings/$tab': typeof AuthenticatedSettingsTabRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/syncs': typeof AuthenticatedSyncsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/webhooks': typeof AuthenticatedWebhooksIndexRoute
  '/users/$userId/$tab': typeof AuthenticatedUsersUserIdTabRoute
  '/webhooks/$endpointId/$tab': typeof AuthenticatedWebhooksEndpointIdTabRoute
  '/users/$userId/pair/error': typeof UsersUserIdPairErrorRoute
  '/users/$userId/pair/success': typeof UsersUserIdPairSuccessRoute
  '/users/$userId': typeof AuthenticatedUsersUserIdIndexRoute
  '/webhooks/$endpointId': typeof AuthenticatedWebhooksEndpointIdIndexRoute
  '/users/$userId/pair': typeof UsersUserIdPairIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/coverage': typeof AuthenticatedCoverageRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/syncs': typeof AuthenticatedSyncsRouteWithChildren
  '/_authenticated/users': typeof AuthenticatedUsersRouteWithChildren
  '/_authenticated/webhooks': typeof AuthenticatedWebhooksRouteWithChildren
  '/widget/connect': typeof WidgetConnectRoute
  '/_authenticated/settings/$tab': typeof AuthenticatedSettingsTabRoute
  '/_authenticated/users/$userId': typeof AuthenticatedUsersUserIdRouteWithChildren
  '/_authenticated/webhooks/$endpointId': typeof AuthenticatedWebhooksEndpointIdRouteWithChildren
  '/users/$userId/pair': typeof UsersUserIdPairRouteWithChildren
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/syncs/': typeof AuthenticatedSyncsIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/webhooks/': typeof AuthenticatedWebhooksIndexRoute
  '/_authenticated/users/$userId/$tab': typeof AuthenticatedUsersUserIdTabRoute
  '/_authenticated/webhooks/$endpointId/$tab': typeof AuthenticatedWebhooksEndpointIdTabRoute
  '/users/$userId/pair/error': typeof UsersUserIdPairErrorRoute
  '/users/$userId/pair/success': typeof UsersUserIdPairSuccessRoute
  '/_authenticated/users/$userId/': typeof AuthenticatedUsersUserIdIndexRoute
  '/_authenticated/webhooks/$endpointId/': typeof AuthenticatedWebhooksEndpointIdIndexRoute
  '/users/$userId/pair/': typeof UsersUserIdPairIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/coverage'
    | '/dashboard'
    | '/settings'
    | '/syncs'
    | '/users'
    | '/webhooks'
    | '/widget/connect'
    | '/settings/$tab'
    | '/users/$userId'
    | '/webhooks/$endpointId'
    | '/users/$userId/pair'
    | '/settings/'
    | '/syncs/'
    | '/users/'
    | '/webhooks/'
    | '/users/$userId/$tab'
    | '/webhooks/$endpointId/$tab'
    | '/users/$userId/pair/error'
    | '/users/$userId/pair/success'
    | '/users/$userId/'
    | '/webhooks/$endpointId/'
    | '/users/$userId/pair/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/coverage'
    | '/dashboard'
    | '/widget/connect'
    | '/settings/$tab'
    | '/settings'
    | '/syncs'
    | '/users'
    | '/webhooks'
    | '/users/$userId/$tab'
    | '/webhooks/$endpointId/$tab'
    | '/users/$userId/pair/error'
    | '/users/$userId/pair/success'
    | '/users/$userId'
    | '/webhooks/$endpointId'
    | '/users/$userId/pair'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/accept-invite'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/_authenticated/coverage'
    | '/_authenticated/dashboard'
    | '/_authenticated/settings'
    | '/_authenticated/syncs'
    | '/_authenticated/users'
    | '/_authenticated/webhooks'
    | '/widget/connect'
    | '/_authenticated/settings/$tab'
    | '/_authenticated/users/$userId'
    | '/_authenticated/webhooks/$endpointId'
    | '/users/$userId/pair'
    | '/_authenticated/settings/'
    | '/_authenticated/syncs/'
    | '/_authenticated/users/'
    | '/_authenticated/webhooks/'
    | '/_authenticated/users/$userId/$tab'
    | '/_authenticated/webhooks/$endpointId/$tab'
    | '/users/$userId/pair/error'
    | '/users/$userId/pair/success'
    | '/_authenticated/users/$userId/'
    | '/_authenticated/webhooks/$endpointId/'
    | '/users/$userId/pair/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  WidgetConnectRoute: typeof WidgetConnectRoute
  UsersUserIdPairRoute: typeof UsersUserIdPairRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/coverage': {
      id: '/_authenticated/coverage'
      path: '/coverage'
      fullPath: '/coverage'
      preLoaderRoute: typeof AuthenticatedCoverageRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/syncs': {
      id: '/_authenticated/syncs'
      path: '/syncs'
      fullPath: '/syncs'
      preLoaderRoute: typeof AuthenticatedSyncsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/webhooks': {
      id: '/_authenticated/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof AuthenticatedWebhooksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/widget/connect': {
      id: '/widget/connect'
      path: '/widget/connect'
      fullPath: '/widget/connect'
      preLoaderRoute: typeof WidgetConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/$tab': {
      id: '/_authenticated/settings/$tab'
      path: '/$tab'
      fullPath: '/settings/$tab'
      preLoaderRoute: typeof AuthenticatedSettingsTabRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/syncs/': {
      id: '/_authenticated/syncs/'
      path: '/'
      fullPath: '/syncs/'
      preLoaderRoute: typeof AuthenticatedSyncsIndexRouteImport
      parentRoute: typeof AuthenticatedSyncsRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedUsersRoute
    }
    '/_authenticated/users/$userId': {
      id: '/_authenticated/users/$userId'
      path: '/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AuthenticatedUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedUsersRoute
    }
    '/_authenticated/webhooks/': {
      id: '/_authenticated/webhooks/'
      path: '/'
      fullPath: '/webhooks/'
      preLoaderRoute: typeof AuthenticatedWebhooksIndexRouteImport
      parentRoute: typeof AuthenticatedWebhooksRoute
    }
    '/_authenticated/webhooks/$endpointId': {
      id: '/_authenticated/webhooks/$endpointId'
      path: '/$endpointId'
      fullPath: '/webhooks/$endpointId'
      preLoaderRoute: typeof AuthenticatedWebhooksEndpointIdRouteImport
      parentRoute: typeof AuthenticatedWebhooksRoute
    }
    '/users/$userId/pair': {
      id: '/users/$userId/pair'
      path: '/users/$userId/pair'
      fullPath: '/users/$userId/pair'
      preLoaderRoute: typeof UsersUserIdPairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users/$userId/': {
      id: '/_authenticated/users/$userId/'
      path: '/'
      fullPath: '/users/$userId/'
      preLoaderRoute: typeof AuthenticatedUsersUserIdIndexRouteImport
      parentRoute: typeof AuthenticatedUsersUserIdRoute
    }
    '/_authenticated/users/$userId/$tab': {
      id: '/_authenticated/users/$userId/$tab'
      path: '/$tab'
      fullPath: '/users/$userId/$tab'
      preLoaderRoute: typeof AuthenticatedUsersUserIdTabRouteImport
      parentRoute: typeof AuthenticatedUsersUserIdRoute
    }
    '/_authenticated/webhooks/$endpointId/': {
      id: '/_authenticated/webhooks/$endpointId/'
      path: '/'
      fullPath: '/webhooks/$endpointId/'
      preLoaderRoute: typeof AuthenticatedWebhooksEndpointIdIndexRouteImport
      parentRoute: typeof AuthenticatedWebhooksEndpointIdRoute
    }
    '/_authenticated/webhooks/$endpointId/$tab': {
      id: '/_authenticated/webhooks/$endpointId/$tab'
      path: '/$tab'
      fullPath: '/webhooks/$endpointId/$tab'
      preLoaderRoute: typeof AuthenticatedWebhooksEndpointIdTabRouteImport
      parentRoute: typeof AuthenticatedWebhooksEndpointIdRoute
    }
    '/users/$userId/pair/': {
      id: '/users/$userId/pair/'
      path: '/'
      fullPath: '/users/$userId/pair/'
      preLoaderRoute: typeof UsersUserIdPairIndexRouteImport
      parentRoute: typeof UsersUserIdPairRoute
    }
    '/users/$userId/pair/error': {
      id: '/users/$userId/pair/error'
      path: '/error'
      fullPath: '/users/$userId/pair/error'
      preLoaderRoute: typeof UsersUserIdPairErrorRouteImport
      parentRoute: typeof UsersUserIdPairRoute
    }
    '/users/$userId/pair/success': {
      id: '/users/$userId/pair/success'
      path: '/success'
      fullPath: '/users/$userId/pair/success'
      preLoaderRoute: typeof UsersUserIdPairSuccessRouteImport
      parentRoute: typeof UsersUserIdPairRoute
    }
  }
}

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsTabRoute: typeof AuthenticatedSettingsTabRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsTabRoute: AuthenticatedSettingsTabRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedSyncsRouteChildren {
  AuthenticatedSyncsIndexRoute: typeof AuthenticatedSyncsIndexRoute
}

const AuthenticatedSyncsRouteChildren: AuthenticatedSyncsRouteChildren = {
  AuthenticatedSyncsIndexRoute: AuthenticatedSyncsIndexRoute,
}

const AuthenticatedSyncsRouteWithChildren =
  AuthenticatedSyncsRoute._addFileChildren(AuthenticatedSyncsRouteChildren)

interface AuthenticatedUsersUserIdRouteChildren {
  AuthenticatedUsersUserIdTabRoute: typeof AuthenticatedUsersUserIdTabRoute
  AuthenticatedUsersUserIdIndexRoute: typeof AuthenticatedUsersUserIdIndexRoute
}

const AuthenticatedUsersUserIdRouteChildren: AuthenticatedUsersUserIdRouteChildren =
  {
    AuthenticatedUsersUserIdTabRoute: AuthenticatedUsersUserIdTabRoute,
    AuthenticatedUsersUserIdIndexRoute: AuthenticatedUsersUserIdIndexRoute,
  }

const AuthenticatedUsersUserIdRouteWithChildren =
  AuthenticatedUsersUserIdRoute._addFileChildren(
    AuthenticatedUsersUserIdRouteChildren,
  )

interface AuthenticatedUsersRouteChildren {
  AuthenticatedUsersUserIdRoute: typeof AuthenticatedUsersUserIdRouteWithChildren
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
}

const AuthenticatedUsersRouteChildren: AuthenticatedUsersRouteChildren = {
  AuthenticatedUsersUserIdRoute: AuthenticatedUsersUserIdRouteWithChildren,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
}

const AuthenticatedUsersRouteWithChildren =
  AuthenticatedUsersRoute._addFileChildren(AuthenticatedUsersRouteChildren)

interface AuthenticatedWebhooksEndpointIdRouteChildren {
  AuthenticatedWebhooksEndpointIdTabRoute: typeof AuthenticatedWebhooksEndpointIdTabRoute
  AuthenticatedWebhooksEndpointIdIndexRoute: typeof AuthenticatedWebhooksEndpointIdIndexRoute
}

const AuthenticatedWebhooksEndpointIdRouteChildren: AuthenticatedWebhooksEndpointIdRouteChildren =
  {
    AuthenticatedWebhooksEndpointIdTabRoute:
      AuthenticatedWebhooksEndpointIdTabRoute,
    AuthenticatedWebhooksEndpointIdIndexRoute:
      AuthenticatedWebhooksEndpointIdIndexRoute,
  }

const AuthenticatedWebhooksEndpointIdRouteWithChildren =
  AuthenticatedWebhooksEndpointIdRoute._addFileChildren(
    AuthenticatedWebhooksEndpointIdRouteChildren,
  )

interface AuthenticatedWebhooksRouteChildren {
  AuthenticatedWebhooksEndpointIdRoute: typeof AuthenticatedWebhooksEndpointIdRouteWithChildren
  AuthenticatedWebhooksIndexRoute: typeof AuthenticatedWebhooksIndexRoute
}

const AuthenticatedWebhooksRouteChildren: AuthenticatedWebhooksRouteChildren = {
  AuthenticatedWebhooksEndpointIdRoute:
    AuthenticatedWebhooksEndpointIdRouteWithChildren,
  AuthenticatedWebhooksIndexRoute: AuthenticatedWebhooksIndexRoute,
}

const AuthenticatedWebhooksRouteWithChildren =
  AuthenticatedWebhooksRoute._addFileChildren(
    AuthenticatedWebhooksRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedCoverageRoute: typeof AuthenticatedCoverageRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedSyncsRoute: typeof AuthenticatedSyncsRouteWithChildren
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRouteWithChildren
  AuthenticatedWebhooksRoute: typeof AuthenticatedWebhooksRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCoverageRoute: AuthenticatedCoverageRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedSyncsRoute: AuthenticatedSyncsRouteWithChildren,
  AuthenticatedUsersRoute: AuthenticatedUsersRouteWithChildren,
  AuthenticatedWebhooksRoute: AuthenticatedWebhooksRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface UsersUserIdPairRouteChildren {
  UsersUserIdPairErrorRoute: typeof UsersUserIdPairErrorRoute
  UsersUserIdPairSuccessRoute: typeof UsersUserIdPairSuccessRoute
  UsersUserIdPairIndexRoute: typeof UsersUserIdPairIndexRoute
}

const UsersUserIdPairRouteChildren: UsersUserIdPairRouteChildren = {
  UsersUserIdPairErrorRoute: UsersUserIdPairErrorRoute,
  UsersUserIdPairSuccessRoute: UsersUserIdPairSuccessRoute,
  UsersUserIdPairIndexRoute: UsersUserIdPairIndexRoute,
}

const UsersUserIdPairRouteWithChildren = UsersUserIdPairRoute._addFileChildren(
  UsersUserIdPairRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  WidgetConnectRoute: WidgetConnectRoute,
  UsersUserIdPairRoute: UsersUserIdPairRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
